server:
  servlet:
    context-path: ${CONTEXT_PATH:/payments/v1}
  forward-headers-strategy: ${SERVER_HEADERS:framework}
  port: 8095
  tomcat:
    connection-timeout: 30s

okhttp:
  trust-all: true

aws:
  credentials:
    key: ${KEY:test}
    secret: ${SECRET:test}
    region: ${REGION:sa-east-1}
  arn:
    basicAuthTokenOmpHub: ${KEY:arn:aws:ssm:sa-east-1:264599301505:parameter/BASIC_AUTH_TOKEN_OMPHUB}
    authHubUserToken: ${KEY:arn:aws:ssm:sa-east-1:264599301505:parameter/projeto-ti/dev/ms-ativacaopixautomatico/AUTH_HUB_USER_TOKEN_OMP}
    authHubPasswordToken: ${KEY:arn:aws:ssm:sa-east-1:264599301505:parameter/projeto-ti/dev/ms-ativacaopixautomatico/AUTH_HUB_PASSWORD_TOKEN}

  sqs:
    queue-url: http://localhost:5001/123456789012/hom-pix-automatico-callback.fifo
    dlq-url: http://localhost:5001/123456789012/hom-pix-automatico-callback-dlq.fifo
    consumer:
      enabled: true
      max-retries-sqs: 3
      max-number-of-messages: 10
      wait-time-seconds: 20

feature:
  async-processing:
    enabled: ${ASYNC_PROCESSING_ENABLED:false}

apigee:
  url: ${APIGEE_URL:https://api-test.claro.com.br}
  credentials:
    basic: ${BASIC:Basic a0dRdVdHdk54MjA1czVDOHg2Vmt6VE84U215UU1XTGc6T0FwRDFvZG9PZ2xvNExRRQ==}

springdoc:
  api-docs:
    path: /api-docs # Customize the OpenAPI documentation endpoint
  swagger-ui:
    enabled: true # Enable or disable Swagger UI

front:
  url: https://dev-jornada-unica.clarobrasil.mobi/?token=

logging:
  level:
    org:
      springframework:
        web: DEBUG

ativacao:
  simplificada:
    loja: 1120
    pdv: LB30

omp:
  journeys:
    url: https://hom-omphub-payment-journey.clarobrasil.mobi

multiplepayment:
  transaction-order-id:
    prefix: "SV"
    suffix-format: "H%d"
    base-length: 10
    max-length: 16

client:
  retry:
    max-retries-api: 3
    retry-delay-api-seconds: 5
  information:
    payment:
      url: /payments/v1/omphub/paymentjourneys/information_payments
  bankinfo:
    url: /payments/v1/claropay/psps
  protocol:
    url: /domains/v1/interactions
  contract:
    subscribers:
      url: /customercontractsubscribers
  sap:
    redemptions:
      url: /ordering/v1/materials/orders/redemptions
    payments:
      url: /ordering/v1/materials/orders/payments
    billing:
      payments:
        url: /customerbill/v1/sap/billingpayments
  transaction:
    notification:
      url: /omphub/transactions/notifications
  apigee:
    token:
      url: /oauth2/v1/token
  communication:
    url: /communication/v1/messages
    campaign: "OS74747"
    templates:
      optin: "adesao_ao_pix_automatico_alterar_forma_de_pgto"
      optout: "alteracao_de_pagamento_para_boleto"
      agendamento: "adesao_ao_pix_automatico_alterar_falha_pgto"
      pagamento: "pix_automatico_pagamento_com_sucesso"
      alteracao: "adesao_ao_pix_automatico_alterar_forma_de_pgto"
      cobranca: "adesao_ao_pix_automatico_alterar_forma_de_pgto"
      falha_agendamento: "adesao_ao_pix_automatico_alterar_falha_agendamento"
      incentivo_adesao: "pix_automatico_incentivo_a_adesao"
    messages:
      optin: "Cliente CLARO, sua fatura foi alterada para Pix Automático. Na sua próxima fatura deve constar a frase PIX AUTOMÁTICO"
      optout: "Cliente CLARO, sua fatura foi alterada para boleto. Consulte mais informações através de nossos canais."
      agendamento: "Cliente CLARO, sua fatura foi alterada para Pix Automático. Na sua próxima fatura deve constar a frase PIX AUTOMÁTICO"
      pagamento: "Cliente CLARO, sua fatura foi paga via Pix Automático. Obrigado! Acompanhe seus pagamentos pelos nossos canais."
      pagamento_avulso: "Cliente CLARO, sua fatura foi paga via Pix Automático. Obrigado! Acompanhe seus pagamentos pelos nossos canais."
      alteracao: "Cliente CLARO, sua fatura foi alterada para Pix Automático. Na sua próxima fatura deve constar a frase PIX AUTOMÁTICO"
      cobranca: "Cliente CLARO, Sua fatura não foi paga via Pix Automático. Atualize seus dados no banco e pague via Pix"
      falha_agendamento: "Cliente CLARO, sua fatura em Pix Automático NÂO foi agendada no seu banco. Regularize seus dados junto ao banco."
      incentivo_adesao: "Cliente CLARO, sua fatura foi cadastrada em PIX Automático. Não esqueça de confirmar o cadastro junto ao seu banco para efetivação do cadastro."
  mobile:
    subscribers:
      url: /mobile/v1/subscribers
      target: test06
    customers:
      billing:
        details:
          url: /mobile/v1/customers/billing/details
          target: test06
  customer:
    residential:
      url: /residential/v1/customers/contracts
      target: test10 #test03
  domains:
    customercontractssubscribers:
      url: /domains/v1/customercontractssubscribers
      target: test10 #test03


